name: Build
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: ./vendor/bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - name: Bundle Install
        run: bundle check || bundle install
      - name: Jekyll build
        run: bundle exec jekyll build
      - name: HTMLProofer tests
        run: |
          bundle exec htmlproofer ./_site \
            --allow-hash-href \
            --check-favicon  \
            --check-html \
            --disable-external
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: '_site'
